/* ============================================================
   Blog posts, the index of every article (newest first) and the
   content of the posts generated by build-posts.js. The first three
   (performance-seo, choosing-your-stack, ar-activations) are
   hand-written pages; for those only the listing data lives here.
   ============================================================ */

module.exports = [
  {
    slug: "generative-search",
    category: "SEO & Growth", filter: "seo",
    date: "September 2026",
    title: "Getting found in AI answers: a practical guide to generative search",
    intro: "Search is turning into answers. Here is how to make sure your business is one of the sources those answers are built from.",
    toc: [["shift", "Search is becoming a conversation"], ["cited", "What gets a page cited"], ["structure", "Structure beats volume"], ["measure", "Measuring what you can't click"]],
    body: `
      <p class="article-lead">A growing share of searches now end in an answer rather than a list of links. AI overviews, chat assistants and answer engines read the web, summarise it and cite a handful of sources. The question for any business is no longer only "do we rank?" but "are we one of the pages the answer is built from?"</p>

      <section id="shift">
        <span class="section-number">01</span>
        <h2>Search is becoming a conversation</h2>
        <p>People ask longer, more specific questions when they expect an answer back: not "web design Dubai" but "how long does it take to build a bilingual website for a real estate company in Dubai?" Generative engines break that question into parts, look for pages that answer each part clearly, and stitch the result together.</p>
        <p>That rewards a different kind of content. Pages that make a clear claim, back it up and say who is saying it are easy to quote. Pages that circle a keyword for 2,000 words without committing to anything are easy to skip.</p>
        <blockquote><p>Classic SEO asks "which page is most relevant?" Generative search asks "which sentence can I trust enough to repeat?"</p></blockquote>
      </section>

      <section id="cited">
        <span class="section-number">02</span>
        <h2>What gets a page cited</h2>
        <p>No engine publishes its full recipe, but the patterns are consistent with everything search has rewarded for years, just more strictly applied:</p>
        <ul class="article-checklist">
          <li><strong>Direct answers, early.</strong><span>Put the answer to the question in the first lines of the section, then explain it.</span></li>
          <li><strong>Specifics over adjectives.</strong><span>Real numbers, named processes, clear conditions. "Usually 8 to 14 weeks, depending on integrations" beats "fast turnaround".</span></li>
          <li><strong>Visible expertise.</strong><span>Who wrote it, what they do, and why they know. Author pages and a clear About page matter.</span></li>
          <li><strong>Consistency across the web.</strong><span>Your name, services and location should match on your site, your profiles and your listings.</span></li>
        </ul>
      </section>

      <section id="structure">
        <span class="section-number">03</span>
        <h2>Structure beats volume</h2>
        <p>Engines parse pages, so structure is how you tell them what each part means. Descriptive headings that read like questions, short paragraphs that each make one point, tables for comparisons and lists for steps all make a page easier to extract from.</p>
        <p>Underneath that, structured data does the same job for machines. Organization, Service, Article and FAQ markup describe who you are and what a page covers in a format engines don't have to guess at. It won't rescue thin content, but it removes ambiguity from good content.</p>
        <p>The technical basics still apply: a page that is slow, blocked from crawling or rendered only after heavy JavaScript is a page an engine may never read properly in the first place.</p>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">The short version</span>
        <strong>Be the clearest answer.</strong>
        <p>Not the longest page, the most quotable one.</p>
      </div>

      <section id="measure">
        <span class="section-number">04</span>
        <h2>Measuring what you can't click</h2>
        <p>Answers don't always send a visit, which makes the old dashboards incomplete. Alongside traffic, track branded search volume, direct visits, enquiries that mention finding you through an assistant, and periodic manual checks of how the main assistants describe your business for the questions your customers actually ask.</p>
        <p>Treat it as an ongoing habit rather than a project: review the questions, tighten the pages that answer them, and keep your facts consistent everywhere they appear.</p>
      </section>
    `,
    cta: ["Want to be the answer?", "Let's review how search sees your site."]
  },
  {
    slug: "technical-seo-launch",
    category: "SEO & Growth", filter: "seo",
    date: "August 2026",
    title: "Technical SEO to get right before launch day",
    intro: "Most ranking problems on a new site are decided before it goes live. This is the checklist we run so launch day starts from a clean slate.",
    toc: [["crawl", "Let search engines in"], ["migrate", "Moving from an old site"], ["pages", "Every page, properly labelled"], ["after", "The first two weeks"]],
    body: `
      <p class="article-lead">A beautiful new website can still launch invisible. The usual causes are not mysterious algorithm changes but small technical oversights: a staging setting left on, redirects that were never mapped, pages that all share the same title. None of them are hard to fix. They are just easy to forget.</p>

      <section id="crawl">
        <span class="section-number">01</span>
        <h2>Let search engines in</h2>
        <p>Staging sites are, rightly, hidden from search engines. The most common launch mistake is carrying that setting into production. Before go-live we check:</p>
        <ul class="article-checklist">
          <li><strong>robots.txt</strong><span>Allows crawling of everything that should be public, and points to the sitemap.</span></li>
          <li><strong>No stray noindex</strong><span>No page-level noindex tags or headers left over from staging.</span></li>
          <li><strong>XML sitemap</strong><span>Lists only real, canonical, indexable pages, and is submitted in Search Console.</span></li>
          <li><strong>One version of the site</strong><span>HTTP, HTTPS, www and non-www all resolve to a single preferred address.</span></li>
        </ul>
      </section>

      <section id="migrate">
        <span class="section-number">02</span>
        <h2>Moving from an old site</h2>
        <p>If the new site replaces an existing one, the old URLs have history: links pointing at them, rankings attached to them, bookmarks. Every one that changes needs a permanent (301) redirect to its closest new equivalent, not to the home page.</p>
        <p>We build the redirect map from the old sitemap, analytics and backlink data before launch, test it on staging, and keep it in place for good. It is the single biggest factor in whether a redesign keeps its traffic.</p>
        <blockquote><p>A redesign without a redirect map is a new website that has to earn every ranking again from zero.</p></blockquote>
      </section>

      <section id="pages">
        <span class="section-number">03</span>
        <h2>Every page, properly labelled</h2>
        <p>Each page should tell search engines clearly what it is. That means a unique title and meta description written for people, one clear H1, a canonical URL, descriptive alt text on meaningful images, and structured data where it fits: Organization on the home page, Service on service pages, Article on posts.</p>
        <p>For bilingual sites, hreflang tags connect each English page to its Arabic counterpart so the right version shows in the right market.</p>
        <p>Performance belongs on this list too. Core Web Vitals are measured on real visits, so a heavy launch build shows up in the data within weeks.</p>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">Rule of thumb</span>
        <strong>Check twice, launch once.</strong>
        <p>Every item here is cheaper before go-live than after.</p>
      </div>

      <section id="after">
        <span class="section-number">04</span>
        <h2>The first two weeks</h2>
        <p>Launch is the start of monitoring, not the end of the project. In the first two weeks we watch Search Console for crawl errors and indexing, follow up on any 404s the redirect map missed, compare traffic against the old site's baseline and fix what surfaces while it is still small.</p>
      </section>
    `,
    cta: ["Launching soon?", "Let's run the pre-launch checks together."]
  },
  {
    slug: "app-launch-checklist",
    category: "Mobile Apps", filter: "mobile",
    date: "August 2026",
    title: "The app launch checklist we run before every release",
    intro: "Shipping to the App Store and Google Play is more than uploading a build. Here is what we line up so launch week is calm.",
    toc: [["store", "The store listing is a product page"], ["watch", "Know when something breaks"], ["review", "Plan for review"], ["launch", "Launch is a sequence, not a moment"]],
    body: `
      <p class="article-lead">The last ten percent of an app project is where schedules slip: a store rejection, a missing privacy answer, a crash nobody could see. None of it is difficult, but all of it takes time if it starts the week you planned to launch. So we start it early and run the same list every time.</p>

      <section id="store">
        <span class="section-number">01</span>
        <h2>The store listing is a product page</h2>
        <p>For most people the store listing is the first impression of your app, and it is a page you have to design like any other. Screenshots that show real value in the first two frames, a name and subtitle that say what it does, a description written for people, and the right category and keywords.</p>
        <p>Both stores also ask detailed questions about data collection and privacy. Answering them accurately means knowing exactly what every SDK in the app collects, so we document that as we build rather than reverse-engineering it at the end.</p>
      </section>

      <section id="watch">
        <span class="section-number">02</span>
        <h2>Know when something breaks</h2>
        <p>Once an app is on thousands of devices, you cannot reproduce every problem yourself. Before release we make sure the app can tell us what is happening:</p>
        <ul class="article-checklist">
          <li><strong>Crash reporting</strong><span>Every crash reported with the device, OS version and the steps that led to it.</span></li>
          <li><strong>Analytics events</strong><span>The key journeys tracked from day one, so you can see where people drop off.</span></li>
          <li><strong>Deep links</strong><span>Links from email, web and campaigns open the right screen, with a sensible fallback if the app isn't installed.</span></li>
          <li><strong>A way to update</strong><span>A minimum-version check or remote config, so a critical fix can reach everyone.</span></li>
        </ul>
      </section>

      <section id="review">
        <span class="section-number">03</span>
        <h2>Plan for review</h2>
        <p>Both stores review apps before they go live, and while review is usually quick, it is not guaranteed. We submit well before the announced date, provide reviewers with a working demo account and clear notes on any features that need hardware, a location or a login, and keep time in the plan for one round of changes.</p>
        <blockquote><p>The launch date you announce should be the day after the build is approved, never the day it is submitted.</p></blockquote>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">Our approach</span>
        <strong>Boring launches.</strong>
        <p>If launch day is exciting, something went wrong earlier.</p>
      </div>

      <section id="launch">
        <span class="section-number">04</span>
        <h2>Launch is a sequence, not a moment</h2>
        <p>Where possible we roll out gradually: a phased release on iOS and a staged rollout on Android let the first users surface issues before everyone has the update. We watch crash rates and reviews closely for the first days, respond to feedback in the stores, and have the first update planned before the first version ships.</p>
      </section>
    `,
    cta: ["Planning an app launch?", "Let's make launch week the easy part."]
  },
  {
    slug: "native-vs-cross-platform",
    category: "Mobile Apps", filter: "mobile",
    date: "July 2026",
    title: "Native, cross-platform or PWA? Choosing your app approach",
    intro: "There's no single right way to build a mobile app. There is a right way for your product, budget and roadmap. Here's how we decide.",
    toc: [["options", "The three options"], ["questions", "The questions that decide it"], ["cost", "The cost nobody quotes"], ["choose", "How we usually land"]],
    body: `
      <p class="article-lead">"Should we build native?" is one of the first questions in almost every app conversation. The honest answer is that it depends on what the app needs to do, who it is for and how it will grow. Each approach is a good choice for some products and an expensive mistake for others.</p>

      <section id="options">
        <span class="section-number">01</span>
        <h2>The three options</h2>
        <ul class="article-checklist">
          <li><strong>Native</strong><span>Separate apps written in Swift for iOS and Kotlin for Android. The most direct access to the platform, the most polished feel, and two codebases to maintain.</span></li>
          <li><strong>Cross-platform</strong><span>One codebase, typically React Native or Flutter, compiled to both platforms. Most of the native feel for most apps, with one team and one set of features to build.</span></li>
          <li><strong>Progressive web app</strong><span>A website that installs to the home screen and works offline. No app store in the way, one codebase shared with the web, but more limited access to device features.</span></li>
        </ul>
      </section>

      <section id="questions">
        <span class="section-number">02</span>
        <h2>The questions that decide it</h2>
        <p>Rather than starting from technology, we start from the product:</p>
        <p><strong>What does it need from the device?</strong> Heavy use of the camera, Bluetooth, background location, AR or complex animations pushes towards native, or towards cross-platform with native modules where needed.</p>
        <p><strong>Does it need the app stores?</strong> Discovery in the stores, in-app purchases and push notifications on every device point to a store app. An internal tool or a companion to a website may not need a store at all.</p>
        <p><strong>How fast does it need to change?</strong> If the product will iterate weekly, one codebase ships every change to everyone at once.</p>
        <blockquote><p>Choose the approach that fits the next three years of the product, not just the first release.</p></blockquote>
      </section>

      <section id="cost">
        <span class="section-number">03</span>
        <h2>The cost nobody quotes</h2>
        <p>The build is only the first cost. Every approach also has to be maintained: OS updates every year, new devices, security patches, store policy changes. Two native codebases roughly double that ongoing work. A PWA has the lowest ongoing cost but relies on what browsers support. Cross-platform sits in between, with the added job of keeping the framework itself up to date.</p>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">The real question</span>
        <strong>What does the product need?</strong>
        <p>Start there, and the technology usually chooses itself.</p>
      </div>

      <section id="choose">
        <span class="section-number">04</span>
        <h2>How we usually land</h2>
        <p>For most business apps, cross-platform gives the best balance of experience, speed and cost. We recommend native when the app lives or dies on deep device features or platform-level polish, and a PWA when reach and simplicity matter more than the store. Whatever the choice, we make it on paper with you first, with the trade-offs written down.</p>
      </section>
    `,
    cta: ["Not sure which way to build?", "Let's map your app before we write code."]
  },
  {
    slug: "bilingual-websites",
    category: "Experience Design", filter: "experience",
    date: "July 2026",
    title: "Designing bilingual websites that feel native in Arabic and English",
    intro: "A bilingual site is not a translated site. Arabic and English read in opposite directions, and good design plans for both from the first sketch.",
    toc: [["mirror", "Right-to-left is a layout, not a setting"], ["type", "Typography in two scripts"], ["content", "Content, not just translation"], ["build", "Building it properly"]],
    body: `
      <p class="article-lead">In the UAE, a website often needs to work equally well for Arabic and English readers. The mistake is to design in English and translate at the end. Arabic reads right to left, uses a different script with different rhythms, and deserves a layout that feels designed for it rather than flipped into it.</p>

      <section id="mirror">
        <span class="section-number">01</span>
        <h2>Right-to-left is a layout, not a setting</h2>
        <p>Switching a page to right-to-left mirrors far more than the text. Navigation, reading order, icons that imply direction such as arrows and progress bars, carousels, form labels and even the side your eye lands on first all change.</p>
        <p>Not everything should flip. Logos, phone numbers, video controls and many numerals stay as they are. Deciding what mirrors and what doesn't is a design decision, and it needs to be made for every component, not left to the browser.</p>
        <blockquote><p>If the Arabic version looks like the English version in a mirror, it wasn't designed. It was reflected.</p></blockquote>
      </section>

      <section id="type">
        <span class="section-number">02</span>
        <h2>Typography in two scripts</h2>
        <p>Arabic and Latin letterforms have different proportions, so the same font size and line height rarely suit both. We pair typefaces designed to sit well together, tune sizes and spacing per language, and test headlines in both, because an Arabic headline may be much shorter or longer than its English equivalent.</p>
        <ul class="article-checklist">
          <li><strong>Paired typefaces</strong><span>A Latin and an Arabic face with matching weight and character.</span></li>
          <li><strong>Per-language spacing</strong><span>Line heights and letter spacing tuned for each script.</span></li>
          <li><strong>Flexible layouts</strong><span>Components that handle text growing or shrinking without breaking.</span></li>
        </ul>
      </section>

      <section id="content">
        <span class="section-number">03</span>
        <h2>Content, not just translation</h2>
        <p>Word-for-word translation often reads awkwardly and can miss the tone that works for an Arabic-speaking audience. The strongest bilingual sites treat Arabic as its own content, written or adapted by native writers, with its own headlines and calls to action. The structure stays shared; the voice belongs to each language.</p>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">Design principle</span>
        <strong>Two first languages.</strong>
        <p>Neither version should feel like the translation.</p>
      </div>

      <section id="build">
        <span class="section-number">04</span>
        <h2>Building it properly</h2>
        <p>On the build side, CSS logical properties (start and end instead of left and right) let one stylesheet serve both directions. Each language gets its own URL, connected with hreflang so search engines show the right version. The CMS lets editors manage both languages side by side, and the language switcher keeps people on the equivalent page instead of sending them back to the home page.</p>
      </section>
    `,
    cta: ["Need a site in Arabic and English?", "Let's design both from day one."]
  },
  {
    slug: "website-timeline",
    category: "Strategy", filter: "strategy",
    date: "June 2026",
    title: "How long does a custom website really take?",
    intro: "The honest answer is \"it depends\", so here is what it depends on, what each phase involves, and what keeps a project on schedule.",
    toc: [["phases", "The four phases"], ["drivers", "What makes it longer"], ["faster", "What keeps it on track"], ["plan", "Planning your launch date"]],
    body: `
      <p class="article-lead">It is usually the first question in any website conversation, and the hardest to answer in one line. A focused marketing site and a platform with bookings, payments and integrations are very different projects. What we can say is where the time goes, and which decisions stretch or shorten it.</p>

      <section id="phases">
        <span class="section-number">01</span>
        <h2>The four phases</h2>
        <ul class="article-checklist">
          <li><strong>Discover</strong><span>Goals, audience, content and technical requirements. The decisions made here shape everything after.</span></li>
          <li><strong>Design</strong><span>Structure and wireframes first, then the visual design of key pages and components, reviewed together.</span></li>
          <li><strong>Build</strong><span>Development, content entry, integrations and testing across devices and browsers.</span></li>
          <li><strong>Launch</strong><span>Final checks, redirects, go-live and the first weeks of monitoring.</span></li>
        </ul>
        <p>As a rough guide, a focused custom marketing site typically takes around two to three months end to end, and larger platforms longer. The phases overlap: content can be written while design progresses, and development can start on agreed components before every page is designed.</p>
      </section>

      <section id="drivers">
        <span class="section-number">02</span>
        <h2>What makes it longer</h2>
        <p>In our experience the biggest schedule risks are rarely technical:</p>
        <p><strong>Content.</strong> Copy, photography and translations arriving late is the most common cause of delay. A site can be finished and still not launch because the words aren't ready.</p>
        <p><strong>Integrations.</strong> Connecting to CRMs, booking systems, payment gateways or internal tools depends on access, documentation and third parties.</p>
        <p><strong>Decision loops.</strong> Many stakeholders reviewing each stage in sequence can double the length of design.</p>
        <blockquote><p>Most website projects are not delayed by building. They are delayed by waiting.</p></blockquote>
      </section>

      <section id="faster">
        <span class="section-number">03</span>
        <h2>What keeps it on track</h2>
        <p>A single decision-maker with the authority to approve, content planned from the first week, clear rounds of feedback with dates attached, and a scope that separates what must be there at launch from what can follow in phase two. Launching a strong core and improving it is almost always better than waiting for everything.</p>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">Best predictor</span>
        <strong>Content, planned early.</strong>
        <p>It is the one part of the schedule only you can deliver.</p>
      </div>

      <section id="plan">
        <span class="section-number">04</span>
        <h2>Planning your launch date</h2>
        <p>If the launch is tied to an event, a campaign or a product release, tell us at the start. We plan backwards from that date, agree what has to be in the first release, and build in time for testing and review rather than squeezing it at the end.</p>
      </section>
    `,
    cta: ["Have a launch date in mind?", "Let's plan the timeline backwards from it."]
  },
  {
    slug: "headless-commerce",
    category: "Engineering", filter: "engineering",
    date: "June 2026",
    title: "Headless commerce: when it's worth the switch",
    intro: "Separating your storefront from your commerce engine can unlock speed and flexibility. It can also add cost you don't need. Here's how to tell.",
    toc: [["what", "What headless actually means"], ["wins", "Where it pays off"], ["costs", "What it costs"], ["decide", "A simple way to decide"]],
    body: `
      <p class="article-lead">"Headless" has become one of the most used words in ecommerce. It describes a real and useful architecture, but it is not an upgrade every store needs. For some businesses it is the right foundation for the next five years. For others, a well-built traditional store would be faster to launch and cheaper to run.</p>

      <section id="what">
        <span class="section-number">01</span>
        <h2>What headless actually means</h2>
        <p>In a traditional platform, the storefront and the commerce engine are one system: the platform manages products and orders and also renders the pages. In a headless setup they are separated. The commerce engine handles products, carts, checkout and orders, and exposes them through an API. A separate front end, built with whatever framework suits the brand, uses that API to create the storefront.</p>
        <p>The same API can feed more than one front end: the website, a mobile app, an in-store kiosk or a marketplace listing.</p>
      </section>

      <section id="wins">
        <span class="section-number">02</span>
        <h2>Where it pays off</h2>
        <ul class="article-checklist">
          <li><strong>Custom experiences</strong><span>Brands whose storefront needs to look and behave in ways a theme can't deliver.</span></li>
          <li><strong>Many channels</strong><span>Selling through web, app and physical touchpoints from one catalogue and one set of orders.</span></li>
          <li><strong>Performance at scale</strong><span>A modern front end can be very fast, which matters for large catalogues and heavy traffic.</span></li>
          <li><strong>Content-led commerce</strong><span>Stores where editorial content and products need to live together, managed in a proper CMS.</span></li>
        </ul>
      </section>

      <section id="costs">
        <span class="section-number">03</span>
        <h2>What it costs</h2>
        <p>Headless moves work from the platform to your team. Features a traditional platform provides out of the box, such as the theme, previews, some apps and plugins, may need to be built or integrated. There are more moving parts to host, monitor and update, and marketing teams need a CMS workflow that genuinely works for them.</p>
        <blockquote><p>Headless gives you total control. That includes control over everything the platform used to do for you.</p></blockquote>
      </section>

      <div class="article-stat">
        <span class="article-stat-label">The trade-off</span>
        <strong>Flexibility for ownership.</strong>
        <p>Worth it when the flexibility earns its keep.</p>
      </div>

      <section id="decide">
        <span class="section-number">04</span>
        <h2>A simple way to decide</h2>
        <p>If your store sells through one channel, a strong theme can express your brand and your team values simplicity, a well-built traditional platform is usually the better choice. If you need several front ends, highly custom experiences or content and commerce deeply combined, and you have the budget to maintain it, headless is worth the switch. Many stores also start traditional and move to headless when they outgrow it, which is a perfectly good plan.</p>
      </section>
    `,
    cta: ["Weighing up headless?", "Let's look at what your store actually needs."]
  },
  // hand-written pages: listing data only
  {
    slug: "performance-seo", category: "Engineering", filter: "engineering", date: "May 2026",
    title: "Why performance is your best SEO strategy", existing: true
  },
  {
    slug: "choosing-your-stack", category: "Strategy", filter: "strategy", date: "April 2026",
    title: "Choosing the right stack for your next build", existing: true
  },
  {
    slug: "ar-activations", category: "Experience Design", filter: "experience", date: "March 2026",
    title: "AR activations that actually activate", existing: true
  }
];
